while(true) func foo() {}   // expect error
